name: layout_grid
description: A CSS-Grid like package for Flutter_web.
version: 1.0.0-dev.2
author: Giovanni Sullutrone <giovisull@gmail.com>
homepage: https://github.com/SirCleric/LayoutGrid

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true