name: layout_grid
description: A CSS-Grid like package for Flutter_web.
version: 0.0.1-dev.2
author: Giovanni Sullutrone <giovisull@gmail.com>
homepage: https://github.com/SirCleric/LayoutGrid

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web: ^0.0.0
  flutter_web_ui: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui