name: basic_example
description: A basic example for the layout_grid library.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  layout_grid: ^1.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true